"""add_jobs_table

Revision ID: b9cab2c01b46
Revises: df634fc5d609
Create Date: 2026-09-01 11:54:11.538128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cab2c01b46'
down_revision: Union[str, Sequence[str], None] = 'df634fc5d609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_type', sa.Enum('PROJECT_REPORT', 'STALE_TASK_SCAN', 'STORY_COMPLETION_CHECK', 'BULK_STATUS_UPDATE', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRYING', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True, comment="Celery's own task UUID"),
    sa.Column('project_id', sa.String(length=36), nullable=True, comment='Related project ID (if applicable)'),
    sa.Column('story_id', sa.String(length=36), nullable=True, comment='Related story ID (if applicable)'),
    sa.Column('input_data', sa.Text(), nullable=True, comment='JSON-encoded job input parameters'),
    sa.Column('result_data', sa.Text(), nullable=True, comment='JSON-encoded job result'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details on failure'),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=True, comment='User or system that triggered this job'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
